version: 0.2
env:
  variables:
    DOTNET_ROOT: /root/.dotnet
cache:
  paths:
    - '/root/.nuget/**/*'
phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
  pre_build:
    commands:
      - echo Restore started on `date`
      - export PATH="$PATH:/root/.dotnet/tools"
      - pip install --upgrade awscli
      - aws configure set profile default
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - echo Incubator Build started on `date`
      - cd code/PokemonSystem.Incubator/ 
      - dotnet lambda deploy-serverless --disable-interactive true --stack-name pokemon-incubator --s3-bucket poke-build-bucket --template serverless.template
      - echo Evolution Build started on `date`
      - cd ../PokemonSystem.Evolution/
      - dotnet lambda deploy-serverless --disable-interactive true --stack-name pokemon-evolution --s3-bucket poke-build-bucket --template serverless.template
      - echo Learning Build started on `date`
      - cd ../PokemonSystem.Learning/
      - dotnet lambda deploy-serverless --disable-interactive true --stack-name pokemon-learning --s3-bucket poke-build-bucket --template serverless.template
      - echo Bills PC started on `date`
      - cd ../PokemonSystem.BillsPC/
      - dotnet lambda deploy-serverless --disable-interactive true --stack-name pokemon-bills-pc --s3-bucket poke-build-bucket --template serverless.template