version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Code/PokemonSystem.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./Build_Output Code/PokemonSystem.sln
artifacts:
  files:
    - Build_Output/**/*
    - appspec.yml
